version: "3.9"

networks:
  bblc_van:
    driver: bridge
    name: bblc_van_net

services:
  webserver:
    image: nginx
    container_name: van_webserver
    restart: unless-stopped
    tty: true
    ports:
      - 6100:80
    volumes:
      - ./api:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - bblc_van

  api:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    container_name: van_api
    working_dir: /var/www/html
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    networks:
      - bblc_van
    environment:
      - TZ=Asia/Manila

  app:
    build:
      context: ./
      dockerfile: ./.docker/next/Dockerfile
      target: app_dev
    container_name: van_app
    stdin_open: true
    tty: true
    ports:
      - "6200:6200"
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - api
    networks:
      - bblc_van
